// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Ejercicio1compraenopencartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ejercicio1compraenopencart() {
    driver.get("http://opencart.abstracta.us/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    js.executeScript("window.scrollTo(0,341)");
    driver.findElement(By.cssSelector(".product-layout:nth-child(1) .hidden-xs")).click();
    js.executeScript("window.scrollTo(0,424)");
    driver.findElement(By.cssSelector(".product-layout:nth-child(4) .hidden-xs")).click();
    driver.findElement(By.id("input-option226")).click();
    {
      WebElement dropdown = driver.findElement(By.id("input-option226"));
      dropdown.findElement(By.xpath("//option[. = 'Blue']")).click();
    }
    driver.findElement(By.id("button-cart")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-default:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > strong")).click();
    driver.findElement(By.cssSelector("tbody:nth-child(2) > tr:nth-child(1) > .text-center")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) > .text-left .btn-danger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa")).click();
    driver.findElement(By.linkText("Desktops")).click();
    driver.findElement(By.linkText("Laptops & Notebooks")).click();
    driver.findElement(By.linkText("Windows (0)")).click();
    driver.findElement(By.linkText("Tablets (1)")).click();
    driver.findElement(By.cssSelector(".button-group .hidden-xs")).click();
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > strong")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(2) .btn-primary"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.linkText("Phones & PDAs")).click();
    driver.findElement(By.cssSelector(".product-layout:nth-child(1) .hidden-xs")).click();
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.cssSelector("tr:nth-child(3) .fa")).click();
    driver.findElement(By.id("cart-total")).click();
    driver.findElement(By.cssSelector("a:nth-child(1) > strong")).click();
    driver.findElement(By.cssSelector(".pull-right > .btn")).click();
    driver.findElement(By.cssSelector(".radio:nth-child(4) input")).click();
    driver.findElement(By.id("button-account")).click();
    {
      WebElement element = driver.findElement(By.linkText("Step 2: Billing Details"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("input-payment-firstname")).click();
    driver.findElement(By.id("input-payment-firstname")).sendKeys("Jonathan Ramiro");
    driver.findElement(By.id("input-payment-lastname")).click();
    driver.findElement(By.id("input-payment-lastname")).sendKeys("Delgado Cruz");
    driver.findElement(By.id("input-payment-email")).click();
    driver.findElement(By.id("input-payment-email")).sendKeys("jrdc023@hotmail.com");
    driver.findElement(By.id("input-payment-telephone")).click();
    driver.findElement(By.id("input-payment-telephone")).sendKeys("0939614209");
    driver.findElement(By.id("input-payment-address-1")).click();
    driver.findElement(By.id("input-payment-address-1")).sendKeys("loja");
    driver.findElement(By.id("input-payment-city")).click();
    driver.findElement(By.id("input-payment-city")).sendKeys("loja");
    driver.findElement(By.id("input-payment-postcode")).click();
    driver.findElement(By.id("input-payment-postcode")).sendKeys("11010");
    driver.findElement(By.id("input-payment-country")).click();
    {
      WebElement dropdown = driver.findElement(By.id("input-payment-country"));
      dropdown.findElement(By.xpath("//option[. = 'Ecuador']")).click();
    }
    driver.findElement(By.id("input-payment-zone")).click();
    {
      WebElement dropdown = driver.findElement(By.id("input-payment-zone"));
      dropdown.findElement(By.xpath("//option[. = 'Loja']")).click();
    }
    driver.findElement(By.id("button-guest")).click();
    js.executeScript("window.scrollTo(0,313)");
    driver.findElement(By.id("button-shipping-method")).click();
    driver.findElement(By.cssSelector("#collapse-payment-method .radio:nth-child(3) input")).click();
    driver.findElement(By.name("agree")).click();
    driver.findElement(By.id("button-payment-method")).click();
    driver.findElement(By.id("button-confirm")).click();
    driver.findElement(By.linkText("Continue")).click();
  }
}
