// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Ejercicio1compraenopencartTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void ejercicio1compraenopencart() {
    driver.Navigate().GoToUrl("http://opencart.abstracta.us/");
    driver.Manage().Window.Size = new System.Drawing.Size(1936, 1048);
    js.ExecuteScript("window.scrollTo(0,341)");
    driver.FindElement(By.CssSelector(".product-layout:nth-child(1) .hidden-xs")).Click();
    js.ExecuteScript("window.scrollTo(0,424)");
    driver.FindElement(By.CssSelector(".product-layout:nth-child(4) .hidden-xs")).Click();
    driver.FindElement(By.Id("input-option226")).Click();
    {
      var dropdown = driver.FindElement(By.Id("input-option226"));
      dropdown.FindElement(By.XPath("//option[. = 'Blue']")).Click();
    }
    driver.FindElement(By.Id("button-cart")).Click();
    {
      var element = driver.FindElement(By.CssSelector(".btn-default:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.CssSelector("a:nth-child(1) > strong")).Click();
    driver.FindElement(By.CssSelector("tbody:nth-child(2) > tr:nth-child(1) > .text-center")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) > .text-left .btn-danger"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.CssSelector("tr:nth-child(2) > .text-left .btn-danger > .fa")).Click();
    driver.FindElement(By.LinkText("Desktops")).Click();
    driver.FindElement(By.LinkText("Laptops & Notebooks")).Click();
    driver.FindElement(By.LinkText("Windows (0)")).Click();
    driver.FindElement(By.LinkText("Tablets (1)")).Click();
    driver.FindElement(By.CssSelector(".button-group .hidden-xs")).Click();
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.CssSelector("a:nth-child(1) > strong")).Click();
    {
      var element = driver.FindElement(By.CssSelector("tr:nth-child(2) .btn-primary"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("Phones & PDAs")).Click();
    driver.FindElement(By.CssSelector(".product-layout:nth-child(1) .hidden-xs")).Click();
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(3) .fa")).Click();
    driver.FindElement(By.Id("cart-total")).Click();
    driver.FindElement(By.CssSelector("a:nth-child(1) > strong")).Click();
    driver.FindElement(By.CssSelector(".pull-right > .btn")).Click();
    driver.FindElement(By.CssSelector(".radio:nth-child(4) input")).Click();
    driver.FindElement(By.Id("button-account")).Click();
    {
      var element = driver.FindElement(By.LinkText("Step 2: Billing Details"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.Id("input-payment-firstname")).Click();
    driver.FindElement(By.Id("input-payment-firstname")).SendKeys("Jonathan Ramiro");
    driver.FindElement(By.Id("input-payment-lastname")).Click();
    driver.FindElement(By.Id("input-payment-lastname")).SendKeys("Delgado Cruz");
    driver.FindElement(By.Id("input-payment-email")).Click();
    driver.FindElement(By.Id("input-payment-email")).SendKeys("jrdc023@hotmail.com");
    driver.FindElement(By.Id("input-payment-telephone")).Click();
    driver.FindElement(By.Id("input-payment-telephone")).SendKeys("0939614209");
    driver.FindElement(By.Id("input-payment-address-1")).Click();
    driver.FindElement(By.Id("input-payment-address-1")).SendKeys("loja");
    driver.FindElement(By.Id("input-payment-city")).Click();
    driver.FindElement(By.Id("input-payment-city")).SendKeys("loja");
    driver.FindElement(By.Id("input-payment-postcode")).Click();
    driver.FindElement(By.Id("input-payment-postcode")).SendKeys("11010");
    driver.FindElement(By.Id("input-payment-country")).Click();
    {
      var dropdown = driver.FindElement(By.Id("input-payment-country"));
      dropdown.FindElement(By.XPath("//option[. = 'Ecuador']")).Click();
    }
    driver.FindElement(By.Id("input-payment-zone")).Click();
    {
      var dropdown = driver.FindElement(By.Id("input-payment-zone"));
      dropdown.FindElement(By.XPath("//option[. = 'Loja']")).Click();
    }
    driver.FindElement(By.Id("button-guest")).Click();
    js.ExecuteScript("window.scrollTo(0,313)");
    driver.FindElement(By.Id("button-shipping-method")).Click();
    driver.FindElement(By.CssSelector("#collapse-payment-method .radio:nth-child(3) input")).Click();
    driver.FindElement(By.Name("agree")).Click();
    driver.FindElement(By.Id("button-payment-method")).Click();
    driver.FindElement(By.Id("button-confirm")).Click();
    driver.FindElement(By.LinkText("Continue")).Click();
  }
}
